version: "3"

services:
    traefik:
        image: traefik:1.7.20
        restart: always
        ports:
            - 80:80
            - 8088:8088
        networks:
            - web
        labels:
            - "traefik.port=80"
            - "traefik.enable=true"
            - traefik.docker.network=web
            - traefik.default.protocol=http
            - "traefik.frontend.rule=Host:monitor.domain.com"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data/traefik.toml:/traefik.toml
        container_name: traefik

networks:
    web:
        external: true
